# Generated by Django 3.2.6 on 2021-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
