# Generated by Django 3.2.6 on 2021-11-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_alter_recipe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
