# Generated by Django 3.2.6 on 2021-11-21 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_auto_20211119_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
