# Generated by Django 3.2.6 on 2021-11-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0006_recipe_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='coverimage',
        ),
    ]
