# Generated by Django 3.2.6 on 2021-11-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0007_rename_image_recipe_coverimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coverimage',
            new_name='coverImage',
        ),
    ]
